name: heal_care
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # For storing data locally.
  shared_preferences: ^2.2.2
  # For theming.
  google_fonts: ^6.2.1
  # For image handling.
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  # For app deployment.
  flutter_native_splash: ^2.0.2
  flutter_launcher_icons: ^0.14.1
  # For networking.
  dio: ^5.4.0
  # For state Management & Logic.
  flutter_bloc: ^8.1.3
  # For responsivity.
  flutter_screenutil: ^5.9.0
  # For dependency injection.
  get_it: ^8.0.2
  # For more return types.
  dartz: ^0.10.1
  # For secured cahce.
  flutter_secure_storage: ^9.2.2
  # For providing a calendar as a horizontal timeline.
  date_picker_timeline: ^1.2.6
  # Firebase dependencies.
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  # Pin code input (OTP) text field.
  pinput: ^5.0.0
  # Flutter integration for Supabase.
  supabase_flutter: ^2.8.1
  persistent_bottom_nav_bar: ^6.2.1


# An extension for generating assets file located in helpers folder.
flutter_assets:
  assets_path: assets/
  output_path: lib/core/helpers/
  filename: app_images.dart
  field_prefix:
# For changing the application icon.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#18A0FB"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  device_preview: ^1.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/icons/
    - assets/images/splash/
    - assets/fonts/poppins/
