// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7as2xkOzoRVcH7D40aLBhUZWSNYF2cPA',
    appId: '1:519935702638:android:bbcf38da6dab3060e9d87f',
    messagingSenderId: '519935702638',
    projectId: 'healcare-79980',
    databaseURL: 'https://healcare-79980-default-rtdb.firebaseio.com',
    storageBucket: 'healcare-79980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVuYviuGJOY2jJefmZRRZTGbZLSFmt-I',
    appId: '1:519935702638:ios:64b6dbfd3858dc57e9d87f',
    messagingSenderId: '519935702638',
    projectId: 'healcare-79980',
    databaseURL: 'https://healcare-79980-default-rtdb.firebaseio.com',
    storageBucket: 'healcare-79980.firebasestorage.app',
    iosClientId: '519935702638-jdvbtfh5lgmklbnrklc91dvrvgj07rrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.healCare',
  );
}
